# Generated by Django 4.2.6 on 2024-10-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_hospital_delete_movies_delete_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='type',
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(default='Unknown Address'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('health_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.healthissue')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hospital')),
            ],
        ),
    ]
