# Generated by Django 4.2.6 on 2024-11-07 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0068_transport_transportdate_transportseattype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportationSeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.transportationdate')),
                ('seat_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.transportationseattype')),
                ('transport_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.transportation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transportdate',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='transportseattype',
            name='transport_date',
        ),
        migrations.RemoveField(
            model_name='transporttickets',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transporttickets',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='transporttickets',
            name='transport_name',
        ),
        migrations.RemoveField(
            model_name='transporttickets',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='transportvenue',
            name='transport',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='TransportDate',
        ),
        migrations.DeleteModel(
            name='TransportSeatType',
        ),
        migrations.DeleteModel(
            name='TransportTickets',
        ),
        migrations.DeleteModel(
            name='TransportVenue',
        ),
        migrations.AddField(
            model_name='transportationtickets',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.transportationvenue'),
        ),
    ]
