# Generated by Django 4.2.6 on 2024-11-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_transportation_transportationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transportationtickets',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transportationtickets',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='transportationtickets',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='transportationtickets',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transportationtickets',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.DeleteModel(
            name='TransportationDate',
        ),
        migrations.DeleteModel(
            name='TransportationSeatType',
        ),
        migrations.DeleteModel(
            name='TransportationTickets',
        ),
        migrations.DeleteModel(
            name='TransportationVenue',
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.buscategory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.cartype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.place'),
        ),
    ]
