# Generated by Django 4.2.11 on 2024-11-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0073_issue_hospital_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthIssue',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
