# Generated by Django 4.2.11 on 2024-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0074_delete_healthissue_delete_hospital_delete_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10)),
                ('issues', models.ManyToManyField(blank=True, to='application.healthissue')),
            ],
        ),
    ]
