# Generated by Django 4.2.11 on 2024-11-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_alter_healthissue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='issues',
        ),
        migrations.DeleteModel(
            name='HealthIssue',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
