# Generated by Django 4.2.11 on 2024-11-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
