# Generated by Django 4.2.11 on 2024-11-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0081_alter_hospital_name_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='health_issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.healthissue'),
            preserve_default=False,
        ),
    ]
